import { Injectable } from '@angular/core';
import { AuthService } from './auth.service';
import { HttpErrorResponse, HttpEvent, HttpHandler, HttpRequest } from '@angular/common/http';
import { catchError, Observable, throwError } from 'rxjs';
import { Router } from '@angular/router';

@Injectable({
  providedIn: 'root'
})
export class ErrorInterceptorService {

  constructor(private authService: AuthService, private router: Router) {}

  intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    return next.handle(req).pipe(
      catchError((error: HttpErrorResponse) => {
        if (error.status === 401) {
          // Si es un error 401, desloguea y redirige al login
          this.authService.logout();
          this.router.navigate(['/login']);
        }

        console.error('Error en la solicitud:', error); // Log del error
        return throwError(() => new Error('Algo fall√≥. Por favor intente nuevamente.'));
      })
    );
  }
}
